/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SokRouteImport } from './routes/sok'
import { Route as AuthenticatedKontoRouteImport } from './routes/_authenticated/konto'
import { Route as AuthenticatedMinaResorRouteImport } from './routes/_authenticated/mina-resor'
import { Route as DeladSlugRouteImport } from './routes/delad.$slug'
import { Route as AuthenticatedResaIdRouteImport } from './routes/_authenticated/resa.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SokRoute = SokRouteImport.update({
  id: '/sok',
  path: '/sok',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKontoRoute = AuthenticatedKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinaResorRoute = AuthenticatedMinaResorRouteImport.update({
  id: '/mina-resor',
  path: '/mina-resor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DeladSlugRoute = DeladSlugRouteImport.update({
  id: '/delad/$slug',
  path: '/delad/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResaIdRoute = AuthenticatedResaIdRouteImport.update({
  id: '/resa/$id',
  path: '/resa/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/integritet': typeof IntegritetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sok': typeof SokRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/mina-resor': typeof AuthenticatedMinaResorRoute
  '/delad/$slug': typeof DeladSlugRoute
  '/resa/$id': typeof AuthenticatedResaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/integritet': typeof IntegritetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sok': typeof SokRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/mina-resor': typeof AuthenticatedMinaResorRoute
  '/delad/$slug': typeof DeladSlugRoute
  '/resa/$id': typeof AuthenticatedResaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/integritet': typeof IntegritetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sok': typeof SokRoute
  '/_authenticated/konto': typeof AuthenticatedKontoRoute
  '/_authenticated/mina-resor': typeof AuthenticatedMinaResorRoute
  '/delad/$slug': typeof DeladSlugRoute
  '/_authenticated/resa/$id': typeof AuthenticatedResaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/integritet'
    | '/sitemap.xml'
    | '/sok'
    | '/konto'
    | '/mina-resor'
    | '/delad/$slug'
    | '/resa/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/integritet'
    | '/sitemap.xml'
    | '/sok'
    | '/konto'
    | '/mina-resor'
    | '/delad/$slug'
    | '/resa/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/integritet'
    | '/sitemap.xml'
    | '/sok'
    | '/_authenticated/konto'
    | '/_authenticated/mina-resor'
    | '/delad/$slug'
    | '/_authenticated/resa/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntegritetRoute: typeof IntegritetRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SokRoute: typeof SokRoute
  DeladSlugRoute: typeof DeladSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sok': {
      id: '/sok'
      path: '/sok'
      fullPath: '/sok'
      preLoaderRoute: typeof SokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/konto': {
      id: '/_authenticated/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AuthenticatedKontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mina-resor': {
      id: '/_authenticated/mina-resor'
      path: '/mina-resor'
      fullPath: '/mina-resor'
      preLoaderRoute: typeof AuthenticatedMinaResorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/delad/$slug': {
      id: '/delad/$slug'
      path: '/delad/$slug'
      fullPath: '/delad/$slug'
      preLoaderRoute: typeof DeladSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resa/$id': {
      id: '/_authenticated/resa/$id'
      path: '/resa/$id'
      fullPath: '/resa/$id'
      preLoaderRoute: typeof AuthenticatedResaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKontoRoute: typeof AuthenticatedKontoRoute
  AuthenticatedMinaResorRoute: typeof AuthenticatedMinaResorRoute
  AuthenticatedResaIdRoute: typeof AuthenticatedResaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKontoRoute: AuthenticatedKontoRoute,
  AuthenticatedMinaResorRoute: AuthenticatedMinaResorRoute,
  AuthenticatedResaIdRoute: AuthenticatedResaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntegritetRoute: IntegritetRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SokRoute: SokRoute,
  DeladSlugRoute: DeladSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
